apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.name }}
  labels:
    app: {{ .Values.project.name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.project.portNumber }}
    name: http
  selector:
    app: {{ .Values.project.name }}
