apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.project.name }}
spec:
  hosts:
  - "{{ .Values.project.name }}.{{ .Values.google.project.ingressgatewayIp }}.nip.io"
  gateways:
  - {{ .Values.google.project.gatewayName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.project.svc }}
        port:
          number: {{ .Values.project.portNumber }}
