apiVersion: v1
kind: Service
metadata:
  name: telemetry-frontend
  labels:
    app: telemetry-frontend
spec:
  ports:
  - protocol: TCP
    port: 8080
    name: http
  selector:
    app: telemetry-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telemetry-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: telemetry-frontend
    spec:
      containers:
      - name: telemetry-frontend
        image: $DOCKER_IMAGE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      - name: fluentd-es
        image: gcr.io/google-containers/fluentd-elasticsearch:v2.0.1
        ports:
        - containerPort: 8888
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-es-config